### ISSUE TITLE
Cross-platform short term roadmap for API freeze

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion#66]
Swift:

- [x] Timeline
- [x] arcMove
- [ ] transition director stacks

Android:

- [x] Spring interaction
- [ ] Timeline
- [ ] Transitions

Web:

Working on prototypes of:
- [x] `createDragStream()`
- [x] 2d springs
- [x] runtime access from within an interaction
- [ ] a bottom sheet DOM demo

**Comment by jverkoey** [comment]
I might defer transition director stacks til post-API freeze.
